# Generated by Django 5.1.7 on 2025-03-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
