# Generated by Django 5.1.7 on 2025-03-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyManager',
        ),
    ]
